export const selectors = [
  {
    id: 1,
    value: "Manufacturing",
    name: "Manufacturing",
  },
  {
    id: 2,
    value: "Other",
    name: "Other",
  },
  {
    id: 3,
    value: "Service",
    name: "Service",
  },
];

export const subSelectors = [
  {
    id: 1,
    sectorId: 1,
    value: "Construction materials",
    name: "Construction materials",
  },
  {
    id: 2,
    sectorId: 1,
    value: "Electronics and Optics",
    name: "Electronics and Optics",
  },
  {
    id: 3,
    sectorId: 1,
    value: "Food and Beverage",
    name: "Food and Beverage",
  },
  {
    id: 4,
    sectorId: 1,
    value: "Furniture",
    name: "Furniture",
  },
  {
    id: 5,
    sectorId: 1,
    value: "Machinery",
    name: "Machinery",
  },
  {
    id: 6,
    sectorId: 1,
    value: "Metalworking",
    name: "Metalworking",
  },
  {
    id: 7,
    sectorId: 1,
    value: "Plastic and Rubber",
    name: "Plastic and Rubber",
  },
  {
    id: 8,
    sectorId: 1,
    value: "Printing",
    name: "Printing",
  },
  {
    id: 9,
    sectorId: 1,
    value: "Textile and Clothing",
    name: "Textile and Clothing",
  },
  {
    id: 10,
    sectorId: 1,
    value: "Wood",
    name: "Wood",
  },
  {
    id: 11,
    sectorId: 2,
    value: "Creative industries",
    name: "Creative industries",
  },
  {
    id: 12,
    sectorId: 2,
    value: "Energy technology",
    name: "Energy technology",
  },
  {
    id: 13,
    sectorId: 2,
    value: "Environment",
    name: "Environment",
  },
  {
    id: 14,
    sectorId: 3,
    value: "Business services",
    name: "Business services",
  },
  {
    id: 14,
    sectorId: 3,
    value: "Information Technology and Telecommunications",
    name: "Information Technology and Telecommunications",
  },
  {
    id: 15,
    sectorId: 3,
    value: "Tourism",
    name: "Tourism",
  },
  {
    id: 16,
    sectorId: 3,
    value: "Translation services",
    name: "Translation services",
  },
  {
    id: 17,
    sectorId: 3,
    value: "Transport and Logistics",
    name: "Transport and Logistics",
  },
];

export const subSelectors1 = [
  {
    id: 1,
    subSelectorsId: 3,
    value: "Bakery & confectionery products",
    name: "Bakery & confectionery products",
  },
  {
    id: 2,
    subSelectorsId: 3,
    value: "Beverages",
    name: "Beverages",
  },
  {
    id: 3,
    subSelectorsId: 3,
    value: "Fish & fish products",
    name: "Fish & fish products",
  },
  {
    id: 4,
    subSelectorsId: 3,
    value: "Meat & meat products",
    name: "Meat & meat products",
  },
  {
    id: 5,
    subSelectorsId: 3,
    value: "Milk & dairy products",
    name: "Milk & dairy products",
  },
  {
    id: 6,
    subSelectorsId: 3,
    value: "Other",
    name: "Other",
  },
  {
    id: 7,
    subSelectorsId: 3,
    value: "Sweets & snack food",
    name: "Sweets & snack food",
  },
  {
    id: 8,
    subSelectorsId: 4,
    value: "Bathroom/sauna",
    name: "Bathroom/sauna",
  },
  {
    id: 9,
    subSelectorsId: 4,
    value: "Bedroom",
    name: "Bedroom",
  },
  {
    id: 10,
    subSelectorsId: 4,
    value: "Children's room",
    name: "Children's room",
  },
  {
    id: 11,
    subSelectorsId: 4,
    value: "Kitchen",
    name: "Kitchen",
  },
  {
    id: 12,
    subSelectorsId: 4,
    value: "Living room",
    name: "Living room",
  },
  {
    id: 13,
    subSelectorsId: 4,
    value: "Office",
    name: "Office",
  },
  {
    id: 14,
    subSelectorsId: 4,
    value: "Other (Furniture)",
    name: "Other (Furniture)",
  },
  {
    id: 15,
    subSelectorsId: 4,
    value: "Outdoor",
    name: "Outdoor",
  },
  {
    id: 16,
    subSelectorsId: 4,
    value: "Project furniture",
    name: "Project furniture",
  },
  {
    id: 17,
    subSelectorsId: 5,
    value: "Machinery components",
    name: "Machinery components",
  },
  {
    id: 18,
    subSelectorsId: 5,
    value: "Machinery equipment/tools",
    name: "Machinery equipment/tools",
  },
  {
    id: 19,
    subSelectorsId: 5,
    value: "Manufacture of machinery",
    name: "Manufacture of machinery",
  },
  {
    id: 20,
    subSelectorsId: 5,
    value: "Maritime",
    name: "Maritime",
  },
  {
    id: 21,
    subSelectorsId: 5,
    value: "Metal structures",
    name: "Metal structures",
  },
  {
    id: 22,
    subSelectorsId: 5,
    value: "Other",
    name: "Other",
  },
  {
    id: 23,
    subSelectorsId: 5,
    value: "Repair and maintenance service",
    name: "Repair and maintenance service",
  },
  {
    id: 23,
    sectorId: 6,
    value: "Construction of metal structures",
    name: "Construction of metal structures",
  },
  {
    id: 24,
    sectorId: 6,
    value: "Construction of metal structures",
    name: "Construction of metal structures",
  },
  {
    id: 25,
    sectorId: 6,
    value: "Houses and buildings",
    name: "Houses and buildings",
  },
  {
    id: 26,
    sectorId: 6,
    value: "Metal products",
    name: "Metal products",
  },
  {
    id: 27,
    sectorId: 6,
    value: "Metal works",
    name: "Metal works",
  },
  {
    id: 28,
    sectorId: 7,
    value: "Packaging",
    name: "Packaging",
  },
  {
    id: 29,
    sectorId: 7,
    value: "Plastic goods",
    name: "Plastic goods",
  },
  {
    id: 30,
    sectorId: 7,
    value: "Plastic processing technology",
    name: "Plastic processing technology",
  },
  {
    id: 31,
    sectorId: 7,
    value: "Plastic profiles",
    name: "Plastic profiles",
  },
  {
    id: 32,
    sectorId: 8,
    value: "Advertising",
    name: "Advertising",
  },
  {
    id: 33,
    sectorId: 8,
    value: "Book/Periodicals printing",
    name: "Book/Periodicals printing",
  },
  {
    id: 34,
    sectorId: 8,
    value: "Labelling and packaging printing",
    name: "Labelling and packaging printing",
  },
  {
    id: 35,
    sectorId: 9,
    value: "Clothing",
    name: "Clothing",
  },
  {
    id: 36,
    sectorId: 9,
    value: "textile",
    name: "textile",
  },
  {
    id: 37,
    sectorId: 10,
    value: "Other (Wood)",
    name: "Other (Wood)",
  },
  {
    id: 38,
    sectorId: 10,
    value: "Wooden building materials)",
    name: "Wooden building materials)",
  },
  {
    id: 39,
    sectorId: 10,
    value: "Wooden houses",
    name: "Wooden houses",
  },
  {
    id: 40,
    sectorId: 14,
    value: "Data processing, Web protals, E-marketing",
    name: "Data processing, Web protals, E-marketing",
  },
  {
    id: 41,
    sectorId: 14,
    value: "Programming, consultancy",
    name: "Programming, consultancy",
  },
  {
    id: 42,
    sectorId: 14,
    value: "Software, Hardware",
    name: "Software, Hardware",
  },
  {
    id: 43,
    sectorId: 14,
    value: "Telecommunications",
    name: "Telecommunications",
  },
  {
    id: 44,
    sectorId: 17,
    value: "Air",
    name: "Air",
  },
  {
    id: 45,
    sectorId: 17,
    value: "Rail",
    name: "Rail",
  },
  {
    id: 46,
    sectorId: 17,
    value: "Road",
    name: "Road",
  },
  {
    id: 47,
    sectorId: 17,
    value: "Water",
    name: "Water",
  },
];

export const subSelectors2 = [
  {
    id: 1,
    subSelectorsId: 20,
    value: "Aluminuim and steel workboats",
    name: "Aluminuim and steel workboats",
  },
  {
    id: 2,
    subSelectorsId: 20,
    value: "Boat/Yacht building",
    name: "Boat/Yacht building",
  },
  {
    id: 3,
    subSelectorsId: 20,
    value: "Ship repair and conversion",
    name: "Ship repair and conversion",
  },
  {
    id: 4,
    subSelectorsId: 27,
    value: "CNC-machining",
    name: "CNC-machining",
  },
  {
    id: 5,
    subSelectorsId: 27,
    value: "Forgings, Fasteners",
    name: "Forgings, Fasteners",
  },
  {
    id: 6,
    subSelectorsId: 27,
    value: "Gas, Plasma, Laser cutting",
    name: "Gas, Plasma, Laser cutting",
  },
  {
    id: 7,
    subSelectorsId: 27,
    value: "MIG, TIG, Aluminum welding",
    name: "MIG, TIG, Aluminum welding",
  },
  {
    id: 8,
    subSelectorsId: 30,
    value: "Blowing",
    name: "Blowing",
  },
  {
    id: 9,
    subSelectorsId: 30,
    value: "Moulding",
    name: "Moulding",
  },
  {
    id: 10,
    subSelectorsId: 30,
    value: "PLastics welding and processing",
    name: "PLastics welding and processing",
  },
];
